version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      timezone: "Europe/Sofia"
    commit-message:
      prefix: "[github-action] "
    assignees:
      - "IliyanKostov9"
    reviewers:
      - "IliyanKostov9"
    labels:
      - "github-action"
      - "dependencies"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Europe/Sofia"
    commit-message:
      prefix: "[gradle] "
    assignees:
      - "IliyanKostov9"
    reviewers:
      - "IliyanKostov9"
    labels:
      - "java"
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      timezone: "Europe/Sofia"
    commit-message:
      prefix: "[docker] "
    assignees:
      - "IliyanKostov9"
    reviewers:
      - "IliyanKostov9"
    labels:
      - "docker"
      - "dependencies"
    # milestone: 4
    #    open-pull-requests-limit: 0
