---
openapi: 3.0.3
info:
  title: com.tuvarna.phd API
  version: "1.0"
paths:
  /api.tuvarna.phd.com/v1/contacts:
    get:
      tags:
      - Contact Controller
      summary: Get contacts
      description: Retrieve all teacher's contacts
      responses:
        "200":
          description: Success
          content:
            application/json: {}
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - Basic Auth: []
  /api.tuvarna.phd.com/v1/teacher/create:
    post:
      tags:
      - Teacher Controller
      summary: Create teacher
      description: Creates a teacher in the system
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TeacherDTO"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TeacherDTO"
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - Basic Auth: []
components:
  schemas:
    TeacherDTO:
      type: object
      properties:
        name:
          type: string
  securitySchemes:
    Basic Auth:
      type: http
      scheme: basic
