when:
  # branch: master
  event: [push]


steps:
  - name: scan-pkgs
    image: renovate/renovate
    environment:
      RENOVATE_TOKEN:
        from_secret: RENOVATE_TOKEN
    commands:
      - renovate Tu-Varna-2019/phd-portal-server --endpoint=https://codeberg.org --platform=gitea --token=$RENOVATE_TOKEN
