when:
  event: cron
  cron: "Renovate"

steps:
  - name: scan-pkgs
    image: renovate/renovate
    environment:
      RENOVATE_TOKEN:
        from_secret: RENOVATE_TOKEN
    commands:
      - renovate $CI_REPO --endpoint=https://codeberg.org --platform=gitea --token=$RENOVATE_TOKEN
