steps:
  - name: scanning
    image: python:3.11.11
    when:
      branch: master
      event: pull_request
      status: success
    commands:
      - echo $GITGUARDIAN_API_KEY
      - echo "Running GitGuardian scan"
      - python -m pip install --upgrade pip
      - pip install ggshield
      - ggshield secret scan repo .
    secrets: [ GITGUARDIAN_API_KEY ]
