# when:
#   branch: master
#   event: [ pull_request]

steps:
  - name: Java test
    image: gradle:jdk21-corretto
    when:
      event: push
      status: success
    commands:
      - chmod +x ./gradlew
      - ./gradlew test -Dtestcontainers.disabled=true
