# when:
#   branch: master
#   event: [ pull_request]
# clone:
#    git:
#      image: woodpeckerci/plugin-git
#      settings:
#        partial: false


steps:
  - name: Java test
    image: gradle:jdk21-corretto
    when:
      event: push
      status: success
    commands:
      - chmod +x ./gradlew
      - ./gradlew test \
          -Dquarkus.datasource.devservices.enabled=false \
          -Dquarkus.datasource.db-kind=h2 \
          -Dquarkus.datasource.jdbc.url=jdbc:h2:mem:test;DB_CLOSE_DELAY=-1 \
          -Dquarkus.datasource.username=sa \
          -Dquarkus.datasource.password=sa
