name: Security scanning

on:
  pull_request:
    branches:
      - master

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  scanning:
    name: Scan for security checks
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: GitGuardian scan
        uses: GitGuardian/ggshield-action@v1.32.2
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

      - name: Sonar scan
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarcloud-github-action@v3.0.0

      - name: "SonarQube Quality result"
        run: |
          echo "Quality Gate status: ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
