name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

    branches:
      - master
    paths:
      - "**"
      - "!.gitignore"
      - "!README.md"

jobs:
  checkout:
    name: Checkout repo
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Save repo to artifact
        uses: actions/upload-artifact@v4
        with:
          name: phd-portal-server
          path: .
          overwrite: true
          if-no-files-found: error
          include-hidden-files: true
          retention-days: 0

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: checkout
    if: ${{ github.actor != 'dependabot[bot]' }}
    strategy:
      fail-fast: false
      matrix:
        java_version: [21]

    steps:
      - name: Download repo artifact
        uses: actions/download-artifact@v4
        with:
          name: phd-portal-server
          path: .

      - name: Set up JDK ${{ matrix.java_version  }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java_version  }}
          distribution: "zulu"

      - name: Unit test
        run: echo "It works!"

  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    needs: test
    strategy:
      fail-fast: false
      matrix:
        java_version: [21]

    steps:
      - name: Download repo artifact
        uses: actions/download-artifact@v4
        with:
          name: phd-portal-server
          path: .

      - name: Set up JDK ${{ matrix.java_version  }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java_version  }}
          distribution: "zulu"

      - name: Run checkstyle
        uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: failure # warning
          fail_on_error: true
          checkstyle_version: "10.20.0"
          workdir: .
          properties_file: ./src/main/resources/application.properties
          checkstyle_config: checkstyle.xml
